// Class: ReadBDT_VBF0HighVPtLowMJJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_VBF0HighVPtLowMJJ
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : ajafari
Date           : Fri Jan 18 13:22:04 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/ajafari/Vjj/CMSSW_9_4_2/src/TopLJets2015/TopAnalysis/macro
Training events: 31601
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
nCuts: "0" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "6.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
j_pt[0]                       j_pt_0_                       j_pt[0]                       leadj_pt                                                        'F'    [50.934967041,1465.84570312]
ystar                         ystar                         ystar                         ystar                                                           'F'    [-4.43096017838,4.6264090538]
mjj                           mjj                           mjj                           mjj                                                             'F'    [500.007110596,999.93560791]
j_qg[1]                       j_qg_1_                       j_qg[1]                       subleadjet_qg                                                   'F'    [-1,1]
balance                       balance                       balance                       balance                                                         'F'    [0.268257379532,977.049499512]
C                             C                             C                             C                                                               'F'    [0.0051687201485,0.978911340237]
dphivj0                       dphivj0                       dphivj0                       dphivj0                                                         'F'    [0.0117211341858,3.14157772064]
j_qg[0]                       j_qg_0_                       j_qg[0]                       leadjet_qg                                                      'F'    [-1,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_VBF0HighVPtLowMJJNode
   
#ifndef BDT_VBF0HighVPtLowMJJNode__def
#define BDT_VBF0HighVPtLowMJJNode__def
   
class BDT_VBF0HighVPtLowMJJNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_VBF0HighVPtLowMJJNode ( BDT_VBF0HighVPtLowMJJNode* left,BDT_VBF0HighVPtLowMJJNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_VBF0HighVPtLowMJJNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_VBF0HighVPtLowMJJNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_VBF0HighVPtLowMJJNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_VBF0HighVPtLowMJJNode*   fLeft;     // pointer to the left daughter node
   BDT_VBF0HighVPtLowMJJNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_VBF0HighVPtLowMJJNode::~BDT_VBF0HighVPtLowMJJNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_VBF0HighVPtLowMJJNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_VBF0HighVPtLowMJJNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_VBF0HighVPtLowMJJ : public IClassifierReader {

 public:

   // constructor
   ReadBDT_VBF0HighVPtLowMJJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_VBF0HighVPtLowMJJ" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "j_pt[0]", "ystar", "mjj", "j_qg[1]", "balance", "C", "dphivj0", "j_qg[0]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_VBF0HighVPtLowMJJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_VBF0HighVPtLowMJJNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_VBF0HighVPtLowMJJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_VBF0HighVPtLowMJJNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_VBF0HighVPtLowMJJNode*)current->GetRight();
         else current=(BDT_VBF0HighVPtLowMJJNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_VBF0HighVPtLowMJJ::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.32486101101853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 625.122, 0, 1, 0.652617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417594,-99) , 
2, 823.504, 0, 0, 0.476057,-99) , 
3, 0.926793, 0, 0, 0.551893,-99) , 
NN(
0, 
0, 
-1, 579.012, 0, -1, 0.333382,-99) , 
7, 0.352042, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.251377);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436101,-99) , 
1, 1.22729, 1, 0, 0.57761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399421,-99) , 
7, 0.113891, 0, 0, 0.555139,-99) , 
NN(
0, 
0, 
-1, 0.876386, 0, -1, 0.373664,-99) , 
2, 565.914, 0, 0, 0.522529,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.19387);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 695.396, 0, 1, 0.563611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286038,-99) , 
0, 306.763, 0, 0, 0.395385,-99) , 
1, -1.38365, 0, 0, 0.540523,-99) , 
NN(
0, 
0, 
-1, 0.857319, 0, -1, 0.383774,-99) , 
3, 0.195908, 0, 0, 0.514543,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.168666);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 683.394, 0, 1, 0.55199,-99) , 
NN(
0, 
0, 
-1, 315.813, 0, -1, 0.421272,-99) , 
1, -1.16353, 0, 0, 0.527786,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440365,-99) , 
4, 30.6708, 1, 0, 0.468405,-99) , 
NN(
0, 
0, 
-1, 0.514524, 0, -1, 0.353235,-99) , 
2, 604.58, 0, 0, 0.433537,-99) , 
7, 0.790968, 0, 0, 0.489575,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.169192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471785,-99) , 
1, 0.631453, 1, 0, 0.538652,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401729,-99) , 
0, 381.534, 0, 0, 0.444744,-99) , 
1, -0.876577, 0, 0, 0.515102,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455371,-99) , 
4, 62.8636, 1, 0, 0.497379,-99) , 
NN(
0, 
0, 
-1, 2.93965, 1, -1, 0.396036,-99) , 
0, 338.091, 0, 0, 0.434317,-99) , 
2, 619.155, 0, 0, 0.488301,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0791137);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616575,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441009,-99) , 
6, 3.02345, 1, 0, 0.499138,-99) , 
0, 552.066, 0, 0, 0.506554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394717,-99) , 
3, 0.0481844, 0, 0, 0.498779,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0933403);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601679,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476214,-99) , 
4, 25.2096, 1, 0, 0.489304,-99) , 
0, 552.066, 0, 0, 0.496736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387763,-99) , 
2, 524.723, 0, 0, 0.488868,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0860572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495901,-99) , 
2, 682.859, 0, 0, 0.530201,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451959,-99) , 
7, 0.930569, 0, 0, 0.479066,-99) , 
1, -0.451468, 0, 0, 0.511319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41237,-99) , 
2, 524.723, 0, 0, 0.504229,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0983482);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489498,-99) , 
1, -0.752456, 0, 0, 0.540709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422697,-99) , 
5, 0.516948, 0, 0, 0.470614,-99) , 
4, 104.701, 1, 0, 0.524164,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424517,-99) , 
7, 0.338476, 0, 0, 0.485171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405736,-99) , 
6, 3.05721, 1, 0, 0.473465,-99) , 
3, 0.620426, 0, 0, 0.505779,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0967569);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480102,-99) , 
4, 103.844, 1, 0, 0.52711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448728,-99) , 
0, 184.391, 0, 0, 0.516848,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4465,-99) , 
1, 0.54282, 1, 0, 0.480371,-99) , 
NN(
0, 
0, 
-1, 63.6163, 0, -1, 0.434217,-99) , 
1, -0.66287, 0, 0, 0.465485,-99) , 
3, 0.620426, 0, 0, 0.498207,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0451577);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.579797, 0, 1, 0.53693,-99) , 
NN(
0, 
0, 
-1, 1.75955, 1, -1, 0.492174,-99) , 
3, 0.989863, 0, 0, 0.502375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424813,-99) , 
2, 524.723, 0, 0, 0.496822,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0639872);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444986,-99) , 
3, 0.0481844, 0, 0, 0.513525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437542,-99) , 
1, 1.86768, 1, 0, 0.50864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425103,-99) , 
7, 0.0288378, 0, 0, 0.504067,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0386948);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.984075, 0, 1, 0.541439,-99) , 
NN(
0, 
0, 
-1, 1.81031, 1, -1, 0.492721,-99) , 
0, 492.053, 0, 0, 0.499016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426414,-99) , 
2, 524.723, 0, 0, 0.493825,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0564516);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.993495, 0, 1, 0.519016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481782,-99) , 
2, 570.191, 1, 0, 0.490731,-99) , 
1, -0.260843, 0, 0, 0.506914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436436,-99) , 
2, 524.723, 0, 0, 0.501889,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.071693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.189061, 0, 1, 0.519564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461826,-99) , 
3, 0.124792, 0, 0, 0.512294,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460806,-99) , 
0, 323.241, 0, 0, 0.492854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383382,-99) , 
2, 553.283, 0, 0, 0.477196,-99) , 
1, 0.467548, 1, 0, 0.49995,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0850206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 290.265, 1, 1, 0.548918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480732,-99) , 
0, 225.932, 1, 0, 0.493551,-99) , 
4, 34.7571, 1, 0, 0.506465,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471792,-99) , 
7, 0.986966, 0, 0, 0.497526,-99) , 
NN(
0, 
0, 
-1, 0.473391, 1, -1, 0.443124,-99) , 
0, 296.892, 0, 0, 0.476323,-99) , 
6, 2.85598, 1, 0, 0.492474,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.043572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466282,-99) , 
7, 0.0486003, 0, 0, 0.508632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464064,-99) , 
0, 166.75, 0, 0, 0.504136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448937,-99) , 
2, 520.643, 0, 0, 0.50086,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0505869);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475228,-99) , 
1, 0.936912, 1, 0, 0.509069,-99) , 
NN(
0, 
0, 
-1, 604.26, 0, -1, 0.48472,-99) , 
3, 0.682825, 0, 0, 0.49935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508441,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426668,-99) , 
3, 0.877374, 1, 0, 0.465324,-99) , 
5, 0.239828, 0, 0, 0.494833,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0495038);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493064,-99) , 
6, 2.79146, 0, 0, 0.509236,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447501,-99) , 
2, 603.542, 0, 0, 0.487516,-99) , 
4, 47.9909, 0, 0, 0.500284,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439137,-99) , 
5, 0.146935, 1, 0, 0.466267,-99) , 
5, 0.239828, 0, 0, 0.495773,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0496694);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494848,-99) , 
0, 304.919, 1, 0, 0.539176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493528,-99) , 
3, 0.227833, 1, 0, 0.501938,-99) , 
7, 0.995671, 0, 0, 0.509966,-99) , 
NN(
0, 
0, 
-1, 1.39381, 1, -1, 0.477847,-99) , 
6, 2.85598, 1, 0, 0.495075,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0534486);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 280.996, 1, 1, 0.540202,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477663,-99) , 
7, 0.973962, 1, 0, 0.509218,-99) , 
7, 0.993717, 0, 0, 0.516975,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438787,-99) , 
1, -1.53185, 0, 0, 0.499022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433723,-99) , 
1, 1.39381, 1, 0, 0.491049,-99) , 
6, 2.85598, 1, 0, 0.504954,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0598063);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.68221, 0, 1, 0.522036,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456814,-99) , 
7, 0.835117, 1, 0, 0.494514,-99) , 
7, 0.93384, 0, 0, 0.507502,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466292,-99) , 
0, 310.807, 0, 0, 0.51035,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456059,-99) , 
6, 3.06682, 0, 0, 0.470861,-99) , 
5, 0.549694, 0, 0, 0.484052,-99) , 
6, 2.85598, 1, 0, 0.496629,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.047775);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466295,-99) , 
7, 0.998926, 1, 0, 0.506101,-99) , 
NN(
0, 
0, 
-1, 543.382, 0, -1, 0.483678,-99) , 
7, 0.93384, 0, 0, 0.494248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44709,-99) , 
6, 3.11128, 1, 0, 0.491951,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0463301);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499205,-99) , 
1, -1.07641, 1, 0, 0.507296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470083,-99) , 
5, 0.239828, 0, 0, 0.502403,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485053,-99) , 
2, 860.716, 0, 0, 0.498464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425099,-99) , 
4, 35.4569, 1, 0, 0.483594,-99) , 
4, 41.9275, 0, 0, 0.495765,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0520434);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.00674, 0, 1, 0.532937,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433716,-99) , 
2, 553.283, 0, 0, 0.500745,-99) , 
1, 0.467548, 1, 0, 0.513183,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482598,-99) , 
1, -0.950237, 1, 0, 0.497627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45871,-99) , 
7, 0.998433, 1, 0, 0.492457,-99) , 
1, -0.260843, 0, 0, 0.504317,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0520836);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492426,-99) , 
6, 2.64065, 0, 0, 0.514165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454555,-99) , 
1, -1.04185, 0, 0, 0.48792,-99) , 
5, 0.402739, 0, 0, 0.505091,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452888,-99) , 
3, 0.28218, 0, 0, 0.501483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43136,-99) , 
4, 35.4569, 1, 0, 0.487271,-99) , 
4, 41.9275, 0, 0, 0.498804,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0603454);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440452,-99) , 
3, 0.974969, 1, 0, 0.496043,-99) , 
3, 0.994637, 0, 0, 0.507951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522956,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475043,-99) , 
0, 430.873, 0, 0, 0.483598,-99) , 
2, 905.263, 0, 0, 0.488887,-99) , 
5, 0.586637, 0, 0, 0.49515,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0860476);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461002,-99) , 
1, -1.27098, 0, 0, 0.513717,-99) , 
NN(
0, 
0, 
-1, 55.2934, 0, -1, 0.463592,-99) , 
1, 1.09816, 1, 0, 0.503825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457181,-99) , 
1, 1.06558, 0, 0, 0.472251,-99) , 
1, -1.1838, 1, 0, 0.483756,-99) , 
0, 366.804, 1, 0, 0.496349,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0267991);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532949,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470497,-99) , 
6, 2.95452, 1, 0, 0.495207,-99) , 
6, 3.06654, 0, 0, 0.498248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458544,-99) , 
6, 3.11128, 1, 0, 0.496318,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0349654);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56154,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495033,-99) , 
7, 0.160675, 0, 0, 0.519678,-99) , 
NN(
0, 
0, 
-1, 0.637176, 0, -1, 0.489639,-99) , 
7, 0.304718, 1, 0, 0.49476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45837,-99) , 
7, 0.0288378, 0, 0, 0.49279,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0362932);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487662,-99) , 
5, 0.378758, 0, 0, 0.522041,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459902,-99) , 
7, 0.637176, 0, 0, 0.498761,-99) , 
7, 0.304718, 1, 0, 0.502727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467155,-99) , 
7, 0.0288378, 0, 0, 0.500804,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0453379);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546111,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46724,-99) , 
2, 843.018, 1, 0, 0.497986,-99) , 
4, 54.1132, 1, 0, 0.502468,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490858,-99) , 
2, 841.662, 0, 0, 0.504614,-99) , 
NN(
0, 
0, 
-1, 0.514746, 0, -1, 0.472261,-99) , 
5, 0.450056, 1, 0, 0.486475,-99) , 
4, 47.9736, 0, 0, 0.495895,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0363506);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496597,-99) , 
0, 314.592, 1, 0, 0.523745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450353,-99) , 
2, 574.577, 0, 0, 0.507979,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455461,-99) , 
6, 2.19124, 0, 0, 0.496524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434936,-99) , 
7, 0.581401, 0, 0, 0.491604,-99) , 
7, 0.418674, 1, 0, 0.495756,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0617232);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494924,-99) , 
5, 0.379168, 0, 0, 0.524517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459474,-99) , 
2, 574.577, 0, 0, 0.510553,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473405,-99) , 
2, 582.109, 1, 0, 0.48204,-99) , 
0, 554.118, 0, 0, 0.485508,-99) , 
7, 0.418674, 1, 0, 0.491855,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0524891);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495221,-99) , 
5, 0.456747, 1, 0, 0.509563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441755,-99) , 
7, 0.968166, 1, 0, 0.481866,-99) , 
1, -1.10329, 0, 0, 0.50413,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538575,-99) , 
NN(
0, 
0, 
-1, -0.458765, 0, -1, 0.471551,-99) , 
1, -1.19949, 1, 0, 0.482648,-99) , 
2, 612.485, 0, 0, 0.497377,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0392411);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485156,-99) , 
0, 465.55, 1, 0, 0.512512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474915,-99) , 
7, 0.987142, 0, 0, 0.494788,-99) , 
7, 0.905181, 1, 0, 0.503422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471848,-99) , 
2, 526.62, 0, 0, 0.501037,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.022579);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479364,-99) , 
3, 0.308456, 0, 0, 0.497142,-99) , 
0, 178.367, 1, 0, 0.499586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469686,-99) , 
0, 146.688, 0, 0, 0.497712,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0256675);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538395,-99) , 
NN(
0, 
0, 
-1, 0.99209, 1, -1, 0.493572,-99) , 
7, 0.997756, 0, 0, 0.497182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471593,-99) , 
7, 0.999112, 1, 0, 0.494952,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0314751);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471463,-99) , 
7, 0.99209, 1, 0, 0.500151,-99) , 
7, 0.997756, 0, 0, 0.50294,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440537,-99) , 
5, 0.501228, 0, 0, 0.479524,-99) , 
7, 0.998926, 1, 0, 0.500581,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0284909);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490611,-99) , 
6, 2.67181, 0, 0, 0.518609,-99) , 
NN(
0, 
0, 
-1, 0.581401, 0, -1, 0.492775,-99) , 
7, 0.418674, 1, 0, 0.497513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472329,-99) , 
7, 0.0555255, 0, 0, 0.495363,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0322264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467964,-99) , 
6, 2.19746, 0, 0, 0.496733,-99) , 
5, 0.643045, 0, 0, 0.518004,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497206,-99) , 
7, 0.304718, 1, 0, 0.501093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47,-99) , 
7, 0.0814237, 0, 0, 0.49773,-99) , 
6, 2.41092, 1, 0, 0.50102,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0468091);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.467102, 1, 1, 0.519122,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466663,-99) , 
2, 610.632, 0, 0, 0.4984,-99) , 
1, -0.451468, 0, 0, 0.511356,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490863,-99) , 
7, 0.191222, 0, 0, 0.50402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464706,-99) , 
7, 0.426929, 1, 0, 0.495119,-99) , 
7, 0.637176, 0, 0, 0.505984,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0246145);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486625,-99) , 
4, 11.5683, 0, 0, 0.521289,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499967,-99) , 
5, 0.439598, 1, 0, 0.505165,-99) , 
NN(
0, 
0, 
-1, 0.993201, 1, -1, 0.487853,-99) , 
5, 0.386373, 0, 0, 0.499552,-99) , 
4, 18.4998, 1, 0, 0.501863,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0511242);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.100755, 0, 1, 0.545795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462612,-99) , 
3, 0.966859, 1, 0, 0.501926,-99) , 
3, 0.989805, 0, 0, 0.512315,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466076,-99) , 
5, 0.441257, 1, 0, 0.507997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466641,-99) , 
3, 0.993349, 1, 0, 0.500298,-99) , 
5, 0.482562, 0, 0, 0.506528,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0467439);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557979,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464573,-99) , 
5, 0.479062, 0, 0, 0.499793,-99) , 
2, 837.941, 0, 0, 0.512523,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481204,-99) , 
6, 2.68188, 0, 0, 0.499023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466903,-99) , 
1, -1.53186, 0, 0, 0.495311,-99) , 
3, 0.989853, 0, 0, 0.499243,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0433184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548569,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462767,-99) , 
7, 0.995383, 1, 0, 0.497347,-99) , 
0, 246.738, 1, 0, 0.513319,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474069,-99) , 
3, 0.312765, 0, 0, 0.498191,-99) , 
NN(
0, 
0, 
-1, 211.489, 1, -1, 0.470107,-99) , 
0, 238.556, 0, 0, 0.490725,-99) , 
6, 2.59863, 1, 0, 0.497009,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0506777);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499159,-99) , 
4, 75.7974, 1, 0, 0.529246,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485749,-99) , 
6, 2.68184, 0, 0, 0.49497,-99) , 
0, 227.014, 1, 0, 0.504349,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486346,-99) , 
4, 18.4998, 1, 0, 0.492199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453496,-99) , 
1, 1.2935, 1, 0, 0.486651,-99) , 
6, 2.75508, 1, 0, 0.493891,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0371575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.483871, 0, 1, 0.536408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481822,-99) , 
4, 94.0405, 0, 0, 0.501821,-99) , 
0, 280.799, 1, 0, 0.51615,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473268,-99) , 
1, 1.29379, 1, 0, 0.50023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453331,-99) , 
6, 2.66295, 0, 0, 0.497023,-99) , 
6, 2.59863, 1, 0, 0.502344,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0385211);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495529,-99) , 
2, 848.605, 1, 0, 0.531735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470595,-99) , 
5, 0.518572, 0, 0, 0.500818,-99) , 
2, 741.198, 0, 0, 0.513076,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478274,-99) , 
2, 777.28, 1, 0, 0.494114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455646,-99) , 
2, 524.712, 0, 0, 0.49139,-99) , 
6, 2.60419, 1, 0, 0.49752,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0496183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 867.868, 1, 1, 0.532935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484218,-99) , 
2, 571.405, 1, 0, 0.498523,-99) , 
2, 741.198, 0, 0, 0.512163,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480988,-99) , 
0, 314.92, 1, 0, 0.513776,-99) , 
NN(
0, 
0, 
-1, 318.172, 0, -1, 0.484375,-99) , 
2, 871.415, 0, 0, 0.489155,-99) , 
6, 2.60419, 1, 0, 0.495656,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_VBF0HighVPtLowMJJ::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_VBF0HighVPtLowMJJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
