// Class: ReadBDT_VBF0LowMJJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_VBF0LowMJJ
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : ajafari
Date           : Fri Nov 16 19:59:41 2018
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/ajafari/Vjj/CMSSW_9_4_2/src/TopLJets2015/TopAnalysis/macro
Training events: 103177
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
nCuts: "0" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "6.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
D                             D                             D                             D                                                               'F'    [7.30773568828e-13,0.941354632378]
C                             C                             C                             C                                                               'F'    [0.00191432610154,0.978911340237]
balance                       balance                       balance                       balance                                                         'F'    [0.204615905881,998.726013184]
jjpt                          jjpt                          jjpt                          jjpt                                                            'F'    [1.02414929867,1512.05419922]
ystar                         ystar                         ystar                         ystar                                                           'F'    [-5.39437770844,5.28063249588]
dphijj                        dphijj                        dphijj                        dphijj                                                          'F'    [-3.14156651497,3.14158058167]
dphivj0                       dphivj0                       dphivj0                       dphivj0                                                         'F'    [0.00399923324585,3.1415886879]
dphivj1                       dphivj1                       dphivj1                       dphivj1                                                         'F'    [0.000110149383545,3.14157629013]
j_pt[1]                       j_pt_1_                       j_pt[1]                       SubleadJetPt                                                    'F'    [0,1759.34570312]
detajj                        detajj                        detajj                        detajj                                                          'F'    [0.000106394290924,8.22631072998]
j_c2_00[0]                    j_c2_00_0_                    j_c2_00[0]                    jet_c2_001                                                      'F'    [-1,0.650705516338]
j_c2_00[1]                    j_c2_00_1_                    j_c2_00[1]                    jet_c2_002                                                      'F'    [-1,0.648723065853]
mjj                           mjj                           mjj                           mjj                                                             'F'    [150.003265381,8966.10839844]
j_qg[0]                       j_qg_0_                       j_qg[0]                       leadjet_qg                                                      'F'    [-1,1]
j_qg[1]                       j_qg_1_                       j_qg[1]                       subleadjet_qg                                                   'F'    [-1,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_VBF0LowMJJNode
   
#ifndef BDT_VBF0LowMJJNode__def
#define BDT_VBF0LowMJJNode__def
   
class BDT_VBF0LowMJJNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_VBF0LowMJJNode ( BDT_VBF0LowMJJNode* left,BDT_VBF0LowMJJNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_VBF0LowMJJNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_VBF0LowMJJNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_VBF0LowMJJNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_VBF0LowMJJNode*   fLeft;     // pointer to the left daughter node
   BDT_VBF0LowMJJNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_VBF0LowMJJNode::~BDT_VBF0LowMJJNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_VBF0LowMJJNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_VBF0LowMJJNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_VBF0LowMJJ : public IClassifierReader {

 public:

   // constructor
   ReadBDT_VBF0LowMJJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_VBF0LowMJJ" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "D", "C", "balance", "jjpt", "ystar", "dphijj", "dphivj0", "dphivj1", "j_pt[1]", "detajj", "j_c2_00[0]", "j_c2_00[1]", "mjj", "j_qg[0]", "j_qg[1]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_VBF0LowMJJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_VBF0LowMJJNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_VBF0LowMJJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_VBF0LowMJJNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_VBF0LowMJJNode*)current->GetRight();
         else current=(BDT_VBF0LowMJJNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_VBF0LowMJJ::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.834203408977724);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 860.977, 0, 1, 0.74776,-99) , 
NN(
0, 
0, 
-1, 438.633, 0, -1, 0.117762,-99) , 
12, 512.489, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.417732);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1668.94, 0, 1, 0.72157,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287061,-99) , 
13, 0.190919, 0, 0, 0.47544,-99) , 
12, 1014.46, 0, 0, 0.559747,-99) , 
NN(
0, 
0, 
-1, 97.2407, 0, -1, 0.187985,-99) , 
12, 427.129, 0, 0, 0.452631,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.374199);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.767051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429539,-99) , 
10, 0.573176, 1, 0, 0.550584,-99) , 
12, 1668.94, 0, 0, 0.599156,-99) , 
NN(
0, 
0, 
-1, 77.3159, 0, -1, 0.339653,-99) , 
12, 860.722, 0, 0, 0.422607,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.286287);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416337,-99) , 
12, 403.272, 0, 0, 0.58486,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414813,-99) , 
14, 0.62183, 0, 0, 0.447296,-99) , 
11, 0.562991, 1, 0, 0.530034,-99) , 
NN(
0, 
0, 
-1, 293.792, 0, -1, 0.300326,-99) , 
8, 67.5313, 0, 0, 0.477122,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.170162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1433.37, 0, 1, 0.550141,-99) , 
NN(
0, 
0, 
-1, 386.099, 0, -1, 0.44914,-99) , 
10, 0.55654, 1, 0, 0.507319,-99) , 
NN(
0, 
0, 
-1, 3.05108, 1, -1, 0.289775,-99) , 
8, 50.5331, 0, 0, 0.480111,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.125169);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635194,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401578,-99) , 
12, 342.507, 0, 0, 0.486225,-99) , 
12, 1430.14, 0, 0, 0.503041,-99) , 
NN(
0, 
0, 
-1, 3.00518, 1, -1, 0.332706,-99) , 
8, 52.1486, 0, 0, 0.480594,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.137044);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1430.14, 0, 1, 0.525021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405035,-99) , 
4, 1.32544, 1, 0, 0.507577,-99) , 
NN(
0, 
0, 
-1, 294.566, 0, -1, 0.418042,-99) , 
8, 110.797, 0, 0, 0.4661,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.189119);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 61.0026, 1, 1, 0.591614,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400181,-99) , 
12, 518.739, 1, 0, 0.541991,-99) , 
NN(
0, 
0, 
-1, 384.66, 0, -1, 0.4386,-99) , 
2, 129.478, 0, 0, 0.45548,-99) , 
12, 1430.14, 0, 0, 0.469479,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.25659);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407715,-99) , 
4, 1.27305, 1, 0, 0.546209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233187,-99) , 
2, 64.6519, 0, 0, 0.415366,-99) , 
12, 360.819, 0, 0, 0.521483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582407,-99) , 
NN(
0, 
0, 
-1, -1.58638, 0, -1, 0.37886,-99) , 
9, 1.36552, 1, 0, 0.43286,-99) , 
4, -1.08851, 0, 0, 0.503266,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.119656);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460623,-99) , 
4, -1.39952, 0, 0, 0.527758,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438924,-99) , 
3, 314.568, 0, 0, 0.460155,-99) , 
11, 0.550086, 1, 0, 0.495752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371747,-99) , 
13, 0.048297, 0, 0, 0.485827,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.125212);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477319,-99) , 
7, 2.32709, 1, 0, 0.565048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421599,-99) , 
6, 3.02817, 1, 0, 0.524909,-99) , 
NN(
0, 
0, 
-1, 0.0702347, 0, -1, 0.462295,-99) , 
9, 3.00581, 0, 0, 0.483757,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0679856);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 436.534, 0, 1, 0.519601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402369,-99) , 
8, 38.9839, 0, 0, 0.513419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423647,-99) , 
10, 0.611272, 1, 0, 0.505605,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.150336);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45484,-99) , 
2, 55.5185, 0, 0, 0.542285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464376,-99) , 
2, 34.7976, 1, 0, 0.490225,-99) , 
12, 512.724, 1, 0, 0.502012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256302,-99) , 
2, 56.2029, 0, 0, 0.435776,-99) , 
12, 294.566, 0, 0, 0.49321,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0938882);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487134,-99) , 
2, 103.844, 1, 0, 0.529252,-99) , 
NN(
0, 
0, 
-1, 3.02298, 1, -1, 0.480553,-99) , 
7, 2.01443, 1, 0, 0.513969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.250222,-99) , 
2, 46.6958, 0, 0, 0.428673,-99) , 
12, 294.566, 0, 0, 0.502791,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.122938);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49219,-99) , 
4, -0.524029, 0, 0, 0.527998,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45771,-99) , 
9, 1.35186, 1, 0, 0.482349,-99) , 
4, 0.629848, 1, 0, 0.513321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329925,-99) , 
2, 80.8568, 0, 0, 0.420229,-99) , 
12, 294.566, 0, 0, 0.501193,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.103337);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489435,-99) , 
4, 0.948242, 1, 0, 0.546015,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453154,-99) , 
1, 0.659414, 1, 0, 0.504032,-99) , 
11, 0.51866, 1, 0, 0.519512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325623,-99) , 
3, 256.114, 0, 0, 0.425782,-99) , 
12, 294.566, 0, 0, 0.507424,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0805256);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.81885, 0, 1, 0.533071,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475421,-99) , 
12, 512.767, 1, 0, 0.487932,-99) , 
11, 0.51866, 1, 0, 0.504543,-99) , 
NN(
0, 
0, 
-1, 40.2591, 0, -1, 0.426955,-99) , 
12, 294.566, 0, 0, 0.494612,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.144031);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452243,-99) , 
4, 1.49098, 1, 0, 0.53118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445204,-99) , 
4, -1.50747, 0, 0, 0.520601,-99) , 
NN(
NN(
0, 
0, 
-1, 0.559444, 1, 1, 0.558131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410346,-99) , 
1, 0.260693, 1, 0, 0.432689,-99) , 
2, 101.126, 0, 0, 0.465985,-99) , 
12, 604.208, 0, 0, 0.496358,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.04906);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446781,-99) , 
6, 3.04004, 1, 0, 0.490699,-99) , 
3, 436.553, 0, 0, 0.496642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430292,-99) , 
13, 0.0659387, 0, 0, 0.490232,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.154311);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 76.5259, 1, 1, 0.532298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424151,-99) , 
7, 0.747258, 1, 0, 0.467321,-99) , 
6, 2.9503, 1, 0, 0.505575,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60833,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427294,-99) , 
4, -1.49433, 1, 0, 0.447603,-99) , 
4, 1.50301, 0, 0, 0.466134,-99) , 
9, 2.39651, 0, 0, 0.484209,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0528004);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554004,-99) , 
NN(
0, 
0, 
-1, 187.986, 0, -1, 0.481196,-99) , 
3, 436.553, 0, 0, 0.487778,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0706365);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 867.358, 1, 1, 0.544301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482046,-99) , 
13, 0.998737, 1, 0, 0.523718,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488145,-99) , 
12, 511.017, 1, 0, 0.506535,-99) , 
NN(
0, 
0, 
-1, 380.804, 0, -1, 0.469216,-99) , 
3, 249.494, 0, 0, 0.488278,-99) , 
10, 0.501703, 1, 0, 0.498735,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0443408);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.216995, 1, 1, 0.513498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450237,-99) , 
14, 0.0470869, 0, 0, 0.508842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416408,-99) , 
12, 188.767, 0, 0, 0.505688,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0762515);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576774,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472261,-99) , 
6, 3.02516, 1, 0, 0.509056,-99) , 
9, 2.49231, 1, 0, 0.530297,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465254,-99) , 
12, 867.552, 1, 0, 0.501812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334171,-99) , 
12, 455.628, 0, 0, 0.464178,-99) , 
2, 41.8628, 0, 0, 0.489821,-99) , 
0, 0.00097779, 1, 0, 0.496939,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0695542);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 252.334, 0, 1, 0.545548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489967,-99) , 
1, 0.390396, 1, 0, 0.524576,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463419,-99) , 
13, 0.662253, 0, 0, 0.493853,-99) , 
NN(
0, 
0, 
-1, 444.769, 0, -1, 0.453795,-99) , 
2, 41.8628, 0, 0, 0.481104,-99) , 
0, 0.00097779, 1, 0, 0.488739,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0638165);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493746,-99) , 
1, 0.444615, 0, 0, 0.529336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49091,-99) , 
12, 440.718, 1, 0, 0.517078,-99) , 
NN(
0, 
0, 
-1, 463.058, 0, -1, 0.476144,-99) , 
3, 352.768, 0, 0, 0.484146,-99) , 
7, 0.398765, 1, 0, 0.489805,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0836423);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488774,-99) , 
10, 0.573752, 0, 0, 0.504502,-99) , 
12, 517.354, 1, 0, 0.512468,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3612,-99) , 
10, 0.605603, 1, 0, 0.501304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346229,-99) , 
2, 30.9188, 0, 0, 0.474802,-99) , 
12, 463.058, 0, 0, 0.502691,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.109634);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479273,-99) , 
4, -1.38138, 0, 0, 0.532441,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445625,-99) , 
1, 0.482353, 0, 0, 0.483258,-99) , 
2, 92.71, 1, 0, 0.518646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560758,-99) , 
NN(
0, 
0, 
-1, 215.487, 0, -1, 0.436737,-99) , 
2, 116.807, 0, 0, 0.465398,-99) , 
12, 463.058, 0, 0, 0.504855,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0777164);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480612,-99) , 
4, 0.319992, 1, 0, 0.514474,-99) , 
12, 511.175, 1, 0, 0.530564,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471734,-99) , 
8, 290.988, 1, 0, 0.507488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457224,-99) , 
4, -1.0474, 1, 0, 0.471702,-99) , 
12, 604.208, 0, 0, 0.490699,-99) , 
0, 0.00139369, 1, 0, 0.498847,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0408768);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565762,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496883,-99) , 
9, 0.510779, 1, 0, 0.503506,-99) , 
NN(
0, 
0, 
-1, 380.804, 0, -1, 0.473173,-99) , 
3, 215.583, 0, 0, 0.493966,-99) , 
12, 1811.68, 0, 0, 0.497381,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0345022);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.349747, 1, 1, 0.552682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499451,-99) , 
3, 225.091, 0, 0, 0.534408,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496568,-99) , 
10, 0.430016, 1, 0, 0.501409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421971,-99) , 
12, 187.986, 0, 0, 0.498732,-99) , 
0, 0.000996584, 1, 0, 0.505059,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0357743);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00139674, 1, 1, 0.513295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454214,-99) , 
6, 3.11792, 1, 0, 0.510375,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0397501);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492119,-99) , 
3, 216.002, 0, 0, 0.508191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464795,-99) , 
14, 0.0470074, 0, 0, 0.504918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441519,-99) , 
10, 0.620763, 1, 0, 0.502319,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0316062);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497466,-99) , 
8, 65.9919, 1, 0, 0.505338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463849,-99) , 
6, 3.10461, 1, 0, 0.502214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439235,-99) , 
12, 188.767, 0, 0, 0.500136,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0318355);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.5007, 0, 1, 0.510581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471762,-99) , 
6, 3.10461, 1, 0, 0.50766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447038,-99) , 
12, 188.767, 0, 0, 0.505663,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.053881);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569238,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482515,-99) , 
14, 0.538098, 0, 0, 0.507652,-99) , 
12, 511.175, 1, 0, 0.521172,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461181,-99) , 
9, 1.93493, 1, 0, 0.525961,-99) , 
NN(
0, 
0, 
-1, 300.578, 0, -1, 0.488299,-99) , 
4, 1.31044, 0, 0, 0.493811,-99) , 
0, 0.00139369, 1, 0, 0.49939,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0721682);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.939807, 1, 1, 0.548721,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451997,-99) , 
1, 0.370435, 0, 0, 0.492959,-99) , 
13, 0.913954, 0, 0, 0.520119,-99) , 
NN(
NN(
0, 
0, 
-1, 3.83204, 0, 1, 0.513679,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441318,-99) , 
7, 2.54659, 0, 0, 0.474227,-99) , 
6, 2.86694, 1, 0, 0.499053,-99) , 
7, 1.26116, 1, 0, 0.507724,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.058295);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493138,-99) , 
8, 138.345, 1, 0, 0.514286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442485,-99) , 
12, 342.507, 0, 0, 0.508495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534796,-99) , 
NN(
0, 
0, 
-1, 0.988473, 1, -1, 0.477918,-99) , 
3, 382.61, 0, 0, 0.486965,-99) , 
7, 1.45632, 1, 0, 0.497125,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.033883);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529868,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490155,-99) , 
12, 512.664, 1, 0, 0.497119,-99) , 
5, 2.7116, 0, 0, 0.501048,-99) , 
12, 1811.68, 0, 0, 0.503359,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.081341);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 62.7871, 1, 1, 0.544919,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464972,-99) , 
4, 0.354655, 1, 0, 0.502459,-99) , 
10, 0.566485, 0, 0, 0.516363,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549459,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469807,-99) , 
4, -1.04932, 1, 0, 0.483758,-99) , 
4, 1.34579, 0, 0, 0.493809,-99) , 
12, 695.364, 0, 0, 0.504175,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.078416);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460664,-99) , 
4, 1.09734, 1, 0, 0.532143,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48547,-99) , 
4, 0.931502, 0, 0, 0.499829,-99) , 
9, 3.10033, 0, 0, 0.509473,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488737,-99) , 
4, -1.44316, 1, 0, 0.51914,-99) , 
NN(
0, 
0, 
-1, -1.59702, 0, -1, 0.460998,-99) , 
9, 2.05492, 1, 0, 0.486063,-99) , 
4, -0.80636, 0, 0, 0.503042,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0440776);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46941,-99) , 
12, 265, 0, 0, 0.508055,-99) , 
9, 4.5007, 0, 0, 0.511883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473248,-99) , 
4, 1.82339, 1, 0, 0.508707,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0579309);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49811,-99) , 
3, 278.784, 1, 0, 0.538198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451265,-99) , 
8, 78.3943, 0, 0, 0.521134,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499487,-99) , 
10, 0.455229, 1, 0, 0.510228,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475244,-99) , 
9, 0.76885, 1, 0, 0.485189,-99) , 
8, 104.347, 1, 0, 0.49622,-99) , 
1, 0.637882, 0, 0, 0.501395,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0385615);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 4.5007, 0, 1, 0.514397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474705,-99) , 
4, -1.9385, 0, 0, 0.511858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461271,-99) , 
10, 0.620763, 1, 0, 0.509787,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0358763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538312,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483561,-99) , 
13, 0.597195, 0, 0, 0.499826,-99) , 
6, 2.33443, 1, 0, 0.504311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460998,-99) , 
11, 0.614922, 1, 0, 0.502123,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.03301);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533843,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490837,-99) , 
7, 1.26116, 1, 0, 0.499473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464254,-99) , 
12, 1361.97, 1, 0, 0.496573,-99) , 
9, 4.5007, 0, 0, 0.49891,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.044585);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492637,-99) , 
13, 0.22656, 1, 0, 0.501295,-99) , 
8, 75.0558, 1, 0, 0.509552,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510261,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484201,-99) , 
3, 289.482, 0, 0, 0.495201,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439137,-99) , 
8, 36.9069, 0, 0, 0.491118,-99) , 
6, 2.8578, 1, 0, 0.500345,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0318416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499752,-99) , 
1, 0.660911, 0, 0, 0.507944,-99) , 
9, 3.88873, 0, 0, 0.514601,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468385,-99) , 
8, 189.606, 1, 0, 0.496953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450149,-99) , 
8, 36.9069, 0, 0, 0.493551,-99) , 
6, 2.8578, 1, 0, 0.504086,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0548695);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571352,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480414,-99) , 
12, 482.883, 0, 0, 0.511232,-99) , 
8, 75.0558, 1, 0, 0.517546,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489023,-99) , 
11, 0.577109, 0, 0, 0.495955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442116,-99) , 
12, 503.088, 1, 0, 0.467446,-99) , 
14, 0.260029, 0, 0, 0.489468,-99) , 
6, 2.8578, 1, 0, 0.50352,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0475039);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363114,-99) , 
2, 20.5233, 0, 0, 0.49817,-99) , 
9, 2.39867, 0, 0, 0.515215,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498307,-99) , 
13, 0.22148, 1, 0, 0.505255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438409,-99) , 
12, 566.22, 0, 0, 0.498366,-99) , 
12, 512.664, 1, 0, 0.503668,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0751953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.594405, 0, 1, 0.523081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462894,-99) , 
14, 0.788166, 0, 0, 0.48654,-99) , 
3, 308.782, 1, 0, 0.512003,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450741,-99) , 
3, 215.487, 0, 0, 0.509063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413939,-99) , 
2, 36.3653, 0, 0, 0.488575,-99) , 
12, 463.058, 0, 0, 0.505992,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0310102);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.864858, 0, 1, 0.511446,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475183,-99) , 
12, 854.308, 1, 0, 0.492742,-99) , 
10, 0.557464, 0, 0, 0.499519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467173,-99) , 
13, 0.0714792, 0, 0, 0.496331,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0328425);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519374,-99) , 
NN(
0, 
0, 
-1, 380.807, 0, -1, 0.488127,-99) , 
2, 167.509, 0, 0, 0.491195,-99) , 
12, 1811.68, 0, 0, 0.493272,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.023982);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1619.64, 0, 1, 0.521466,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495796,-99) , 
3, 436.553, 0, 0, 0.498542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462352,-99) , 
12, 1361.86, 1, 0, 0.496063,-99) , 
9, 3.96846, 0, 0, 0.499191,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0415263);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443089,-99) , 
9, 1.66575, 0, 0, 0.534631,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491193,-99) , 
14, 0.648928, 1, 0, 0.500866,-99) , 
8, 57.6309, 1, 0, 0.505184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479314,-99) , 
6, 3.09787, 1, 0, 0.50288,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0350943);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.432544, 1, 1, 0.509935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462863,-99) , 
9, 1.28381, 0, 0, 0.498805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45794,-99) , 
6, 2.87781, 1, 0, 0.483076,-99) , 
11, 0.589532, 1, 0, 0.504666,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0279282);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491755,-99) , 
11, 0.526335, 1, 0, 0.516383,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495229,-99) , 
1, 0.173043, 1, 0, 0.497988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471803,-99) , 
12, 1372.88, 1, 0, 0.495087,-99) , 
10, 0.452584, 1, 0, 0.498069,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0261894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 57.0051, 1, 1, 0.522281,-99) , 
NN(
NN(
0, 
0, 
-1, 57.2584, 1, 1, 0.506357,-99) , 
NN(
0, 
0, 
-1, 42.7077, 0, -1, 0.479351,-99) , 
6, 3.00588, 1, 0, 0.500829,-99) , 
7, 0.398765, 1, 0, 0.503514,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0195322);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460632,-99) , 
4, 1.86352, 1, 0, 0.497984,-99) , 
6, 2.34548, 1, 0, 0.501338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476009,-99) , 
11, 0.609126, 1, 0, 0.499314,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0359906);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521781,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484829,-99) , 
13, 0.801289, 0, 0, 0.499542,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42667,-99) , 
13, 0.988228, 1, 0, 0.480011,-99) , 
7, 2.2061, 1, 0, 0.494117,-99) , 
3, 478.729, 0, 0, 0.49583,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0510001);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490133,-99) , 
2, 60.6679, 1, 0, 0.523268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440199,-99) , 
12, 425.761, 0, 0, 0.489332,-99) , 
13, 0.619892, 0, 0, 0.501282,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490362,-99) , 
6, 2.45957, 1, 0, 0.497695,-99) , 
NN(
0, 
0, 
-1, 0.50114, 1, -1, 0.471466,-99) , 
11, 0.562704, 1, 0, 0.487406,-99) , 
10, 0.557464, 0, 0, 0.493188,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.02948);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491668,-99) , 
13, 0.995618, 1, 0, 0.516871,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485005,-99) , 
13, 0.607184, 0, 0, 0.496869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467207,-99) , 
8, 320.128, 1, 0, 0.49423,-99) , 
10, 0.452584, 1, 0, 0.497395,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0302213);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4967,-99) , 
8, 104.055, 1, 0, 0.51879,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490045,-99) , 
12, 731.447, 0, 0, 0.495695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471126,-99) , 
12, 1372.88, 1, 0, 0.492974,-99) , 
10, 0.452584, 1, 0, 0.496582,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0464347);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584216,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392988,-99) , 
2, 19.7839, 0, 0, 0.496753,-99) , 
9, 2.39867, 0, 0, 0.512497,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492936,-99) , 
9, 1.04244, 1, 0, 0.499479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440113,-99) , 
12, 566.22, 0, 0, 0.493355,-99) , 
12, 512.659, 1, 0, 0.499343,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0334558);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495858,-99) , 
14, 0.740244, 0, 0, 0.524097,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48397,-99) , 
12, 465.45, 0, 0, 0.501089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474946,-99) , 
8, 305.166, 1, 0, 0.498469,-99) , 
10, 0.452584, 1, 0, 0.502048,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0234084);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.995618, 1, 1, 0.523968,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525441,-99) , 
NN(
0, 
0, 
-1, 265.009, 0, -1, 0.493873,-99) , 
12, 225.873, 1, 0, 0.496028,-99) , 
10, 0.452584, 1, 0, 0.499928,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0197416);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536467,-99) , 
NN(
NN(
0, 
0, 
-1, 57.6041, 1, 1, 0.504224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463315,-99) , 
9, 4.18863, 1, 0, 0.501406,-99) , 
12, 1689.82, 0, 0, 0.503467,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0219285);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531555,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496156,-99) , 
8, 57.6041, 1, 0, 0.499289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468232,-99) , 
9, 4.18863, 1, 0, 0.49715,-99) , 
12, 1689.82, 0, 0, 0.499172,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.018036);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544066,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454919,-99) , 
12, 265.009, 0, 0, 0.502447,-99) , 
12, 225.873, 1, 0, 0.503994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464345,-99) , 
12, 187.986, 0, 0, 0.502746,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0274376);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492347,-99) , 
12, 632.293, 0, 0, 0.515786,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494629,-99) , 
5, -2.29995, 1, 0, 0.498688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467594,-99) , 
5, -2.72231, 0, 0, 0.496337,-99) , 
7, 0.398765, 1, 0, 0.498773,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0204287);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52284,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498191,-99) , 
6, 3.07167, 0, 0, 0.502637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467412,-99) , 
8, 37.9064, 0, 0, 0.5011,-99) , 
10, 0.43017, 1, 0, 0.503237,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0339746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540118,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496691,-99) , 
7, 1.4581, 1, 0, 0.505336,-99) , 
12, 1296.4, 0, 0, 0.509752,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546072,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466209,-99) , 
12, 874.166, 1, 0, 0.486868,-99) , 
12, 318.521, 1, 0, 0.495651,-99) , 
4, -0.899564, 0, 0, 0.50619,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0468789);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.17861, 1, 1, 0.51347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472059,-99) , 
13, 0.998788, 1, 0, 0.509281,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466782,-99) , 
12, 881.043, 1, 0, 0.50058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414108,-99) , 
12, 383.666, 0, 0, 0.493083,-99) , 
7, 0.780887, 0, 0, 0.505009,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0322414);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485108,-99) , 
1, 0.379405, 0, 0, 0.498096,-99) , 
12, 1296.4, 0, 0, 0.501963,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529738,-99) , 
NN(
0, 
0, 
-1, 289.262, 0, -1, 0.477981,-99) , 
12, 318.521, 1, 0, 0.485633,-99) , 
4, -0.899564, 0, 0, 0.49784,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0339906);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49615,-99) , 
8, 104.055, 1, 0, 0.513678,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490929,-99) , 
9, 3.63982, 0, 0, 0.496241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468197,-99) , 
8, 46.2451, 0, 0, 0.493795,-99) , 
10, 0.452584, 1, 0, 0.49656,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0227611);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524878,-99) , 
NN(
NN(
0, 
0, 
-1, 319.332, 1, 1, 0.504356,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385783,-99) , 
12, 383.661, 0, 0, 0.481307,-99) , 
3, 186.691, 0, 0, 0.50058,-99) , 
6, 2.11689, 1, 0, 0.502224,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.025817);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519198,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49481,-99) , 
12, 319.332, 1, 0, 0.498666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39119,-99) , 
12, 383.661, 0, 0, 0.47797,-99) , 
3, 186.691, 0, 0, 0.495277,-99) , 
6, 2.11689, 1, 0, 0.496895,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0469299);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487912,-99) , 
8, 108.057, 1, 0, 0.525098,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485069,-99) , 
12, 566.199, 0, 0, 0.499583,-99) , 
1, 0.222669, 1, 0, 0.503341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536706,-99) , 
NN(
0, 
0, 
-1, 1.43798, 0, -1, 0.457224,-99) , 
1, 0.543625, 0, 0, 0.482536,-99) , 
3, 186.542, 0, 0, 0.499514,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0468375);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581811,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480656,-99) , 
4, 0.998253, 0, 0, 0.49794,-99) , 
9, 2.39867, 0, 0, 0.513023,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465015,-99) , 
7, 2.46073, 1, 0, 0.496129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452203,-99) , 
12, 566.22, 0, 0, 0.491608,-99) , 
12, 512.659, 1, 0, 0.4983,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0667807);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562343,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446156,-99) , 
3, 213.536, 0, 0, 0.501013,-99) , 
9, 2.14336, 0, 0, 0.515869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486348,-99) , 
2, 24.4465, 1, 0, 0.495332,-99) , 
NN(
0, 
0, 
-1, 222.15, 1, -1, 0.469174,-99) , 
4, 0.467561, 1, 0, 0.485683,-99) , 
12, 512.664, 1, 0, 0.495109,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0315793);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464392,-99) , 
11, 0.609172, 1, 0, 0.508776,-99) , 
NN(
0, 
0, 
-1, 270.096, 0, -1, 0.492616,-99) , 
2, 47.6718, 0, 0, 0.502564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465954,-99) , 
8, 36.8701, 0, 0, 0.501146,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0343265);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53843,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542368,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484708,-99) , 
13, 0.949821, 1, 0, 0.498363,-99) , 
7, 0.970136, 1, 0, 0.510192,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496209,-99) , 
2, 17.5405, 1, 0, 0.499785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465668,-99) , 
9, 0.415306, 0, 0, 0.496616,-99) , 
10, 0.501154, 1, 0, 0.500568,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0348048);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526464,-99) , 
NN(
NN(
0, 
0, 
-1, 4.32819, 0, 1, 0.507974,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432959,-99) , 
8, 73.2, 0, 0, 0.482426,-99) , 
6, 3.0572, 1, 0, 0.504017,-99) , 
7, 2.86549, 0, 0, 0.50582,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0172308);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51778,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496479,-99) , 
12, 227.368, 1, 0, 0.498032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442684,-99) , 
12, 189.459, 0, 0, 0.49654,-99) , 
7, 2.86549, 0, 0, 0.498245,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00918725);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523008,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499929,-99) , 
12, 225.873, 1, 0, 0.501347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463527,-99) , 
12, 187.986, 0, 0, 0.500188,-99) , 
3, 478.729, 0, 0, 0.501606,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0335471);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.233267, 0, 1, 0.51072,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484941,-99) , 
3, 219.93, 1, 0, 0.496991,-99) , 
4, 0.224428, 1, 0, 0.504623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478776,-99) , 
13, 0.0223128, 0, 0, 0.503465,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0432157);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492031,-99) , 
10, 0.537152, 1, 0, 0.529504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49362,-99) , 
6, 2.42534, 1, 0, 0.500762,-99) , 
4, 0.224428, 1, 0, 0.507305,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495136,-99) , 
1, 0.344819, 1, 0, 0.504171,-99) , 
NN(
0, 
0, 
-1, 382.663, 0, -1, 0.466212,-99) , 
3, 219.489, 0, 0, 0.491644,-99) , 
4, -0.246502, 0, 0, 0.500626,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0369084);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.000262871, 1, 1, 0.51342,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484285,-99) , 
14, 0.979199, 1, 0, 0.508228,-99) , 
NN(
0, 
0, 
-1, 382.663, 0, -1, 0.47731,-99) , 
3, 219.489, 0, 0, 0.498066,-99) , 
4, -0.233267, 0, 0, 0.506805,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0559529);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546687,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485296,-99) , 
14, 0.686532, 1, 0, 0.501084,-99) , 
13, 0.933929, 0, 0, 0.507658,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482937,-99) , 
2, 71.9685, 1, 0, 0.518357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479191,-99) , 
1, 0.222967, 1, 0, 0.487043,-99) , 
14, 0.965639, 0, 0, 0.495891,-99) , 
10, 0.548042, 0, 0, 0.501452,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0511735);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473077,-99) , 
12, 466.622, 0, 0, 0.523659,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494551,-99) , 
5, 2.38317, 0, 0, 0.500043,-99) , 
14, 0.923073, 0, 0, 0.508569,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47697,-99) , 
3, 215.403, 0, 0, 0.505768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448025,-99) , 
8, 164.129, 1, 0, 0.48998,-99) , 
1, 0.279482, 0, 0, 0.50431,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0585721);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476527,-99) , 
4, 1.12014, 1, 0, 0.518949,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487442,-99) , 
4, 1.13346, 0, 0, 0.500038,-99) , 
9, 1.6163, 0, 0, 0.511236,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53243,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450326,-99) , 
9, 3.04131, 0, 0, 0.481507,-99) , 
12, 428.799, 1, 0, 0.491027,-99) , 
1, 0.279482, 0, 0, 0.506608,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0374356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.637882, 0, 1, 0.512081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476555,-99) , 
8, 42.6822, 0, 0, 0.509777,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519562,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447419,-99) , 
8, 103.186, 1, 0, 0.475418,-99) , 
9, 1.70895, 1, 0, 0.485645,-99) , 
1, 0.279482, 0, 0, 0.504249,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0409149);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555456,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49373,-99) , 
1, 0.64319, 0, 0, 0.501919,-99) , 
8, 49.2834, 1, 0, 0.504864,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485396,-99) , 
8, 124.907, 0, 0, 0.516644,-99) , 
NN(
0, 
0, 
-1, -1.30508, 0, -1, 0.480774,-99) , 
9, 1.79567, 1, 0, 0.489367,-99) , 
0, 0.0137202, 0, 0, 0.497428,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0211398);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1296.34, 0, 1, 0.50591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458192,-99) , 
4, 0.387826, 0, 0, 0.477002,-99) , 
6, 2.85747, 1, 0, 0.491286,-99) , 
1, 0.279482, 0, 0, 0.502563,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0428899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547206,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406411,-99) , 
2, 20.5233, 0, 0, 0.494662,-99) , 
9, 2.20363, 0, 0, 0.506502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519774,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479308,-99) , 
12, 1056.2, 0, 0, 0.489045,-99) , 
13, 0.200408, 1, 0, 0.494252,-99) , 
12, 512.659, 1, 0, 0.498068,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0415209);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489781,-99) , 
3, 330.469, 0, 0, 0.496266,-99) , 
12, 742.893, 0, 0, 0.50062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516568,-99) , 
NN(
0, 
0, 
-1, 1025.22, 0, -1, 0.475086,-99) , 
10, 0.570425, 0, 0, 0.487325,-99) , 
12, 849.819, 1, 0, 0.496184,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0235667);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484735,-99) , 
7, 1.33655, 1, 0, 0.521625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498061,-99) , 
13, 0.221492, 1, 0, 0.500262,-99) , 
9, 0.605507, 1, 0, 0.503004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420925,-99) , 
9, 1.11203, 0, 0, 0.481002,-99) , 
13, 0.111714, 0, 0, 0.500228,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0264217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.812239, 1, 1, 0.515419,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497939,-99) , 
5, -2.25028, 1, 0, 0.503203,-99) , 
11, 0.516498, 1, 0, 0.507373,-99) , 
NN(
0, 
0, 
-1, 1.11203, 0, -1, 0.478239,-99) , 
13, 0.111714, 0, 0, 0.503698,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0357857);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.511511, 1, 1, 0.510772,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480418,-99) , 
14, 0.811974, 1, 0, 0.496646,-99) , 
11, 0.489809, 0, 0, 0.507444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433158,-99) , 
9, 1.11203, 0, 0, 0.484836,-99) , 
13, 0.111714, 0, 0, 0.504593,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0211958);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521813,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488742,-99) , 
6, 2.64341, 0, 0, 0.499622,-99) , 
14, 0.997562, 0, 0, 0.50155,-99) , 
NN(
0, 
0, 
-1, 437.657, 0, -1, 0.480631,-99) , 
13, 0.111714, 0, 0, 0.498913,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_VBF0LowMJJ::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_VBF0LowMJJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
