// Class: ReadBDT_VBF0LowVPtHighMJJ
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_VBF0LowVPtHighMJJ
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : ajafari
Date           : Wed Mar 13 15:50:06 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/ajafari/Vjj/CMSSW_9_4_2/src/TopLJets2015/TopAnalysis/macro
Training events: 26262
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
nCuts: "0" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "6.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
ystar                         ystar                         ystar                         			 ystar                                                       'F'    [-3.5614168644,3.07476449013]
mjj                           mjj                           mjj                           			 mjj                                                         'F'    [1000.02545166,9690.50488281]
dphijj                        dphijj                        dphijj                        			 dphijj                                                      'F'    [-3.14146089554,3.14152264595]
j_qg[0]                       j_qg_0_                       j_qg[0]                       			 leadjet_qg                                                  'F'    [-1,1]
dphibjj                       dphibjj                       dphibjj                       			 dphibjj                                                     'F'    [-3.14157533646,3.14157009125]
dphivj0                       dphivj0                       dphivj0                       			 dphivj0                                                     'F'    [0.00175261497498,3.14147353172]
j_qg[1]                       j_qg_1_                       j_qg[1]                       			 subleadjet_qg                                               'F'    [-1,1]
C                             C                             C                             			 C                                                           'F'    [0.0107004772872,0.72715306282]
jjpt                          jjpt                          jjpt                          						 jjpt                                                     'F'    [1.5927734375,636.596374512]
j_pt[0]+j_pt[1]+gamma_pt[0]     j_pt_0__P_j_pt_1__P_gamma_pt_0_ j_pt[0]+j_pt[1]+gamma_pt[0]     syspt                                                               'F'    [177.845947266,1807.64550781]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_VBF0LowVPtHighMJJNode
   
#ifndef BDT_VBF0LowVPtHighMJJNode__def
#define BDT_VBF0LowVPtHighMJJNode__def
   
class BDT_VBF0LowVPtHighMJJNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_VBF0LowVPtHighMJJNode ( BDT_VBF0LowVPtHighMJJNode* left,BDT_VBF0LowVPtHighMJJNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_VBF0LowVPtHighMJJNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_VBF0LowVPtHighMJJNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_VBF0LowVPtHighMJJNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_VBF0LowVPtHighMJJNode*   fLeft;     // pointer to the left daughter node
   BDT_VBF0LowVPtHighMJJNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_VBF0LowVPtHighMJJNode::~BDT_VBF0LowVPtHighMJJNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_VBF0LowVPtHighMJJNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_VBF0LowVPtHighMJJNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_VBF0LowVPtHighMJJ : public IClassifierReader {

 public:

   // constructor
   ReadBDT_VBF0LowVPtHighMJJ( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_VBF0LowVPtHighMJJ" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "ystar", "mjj", "dphijj", "j_qg[0]", "dphibjj", "dphivj0", "j_qg[1]", "C", "jjpt", "j_pt[0]+j_pt[1]+gamma_pt[0]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_VBF0LowVPtHighMJJ() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_VBF0LowVPtHighMJJNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_VBF0LowVPtHighMJJ::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_VBF0LowVPtHighMJJNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_VBF0LowVPtHighMJJNode*)current->GetRight();
         else current=(BDT_VBF0LowVPtHighMJJNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_VBF0LowVPtHighMJJ::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.372145331633741);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 175.813, 1, 1, 0.734443,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31689,-99) , 
0, 0.787898, 1, 0, 0.474451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.189289,-99) , 
0, -1.59123, 0, 0, 0.437265,-99) , 
1, 1734.24, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.260701);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2134.27, 0, 1, 0.697111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495757,-99) , 
8, 175.813, 1, 0, 0.655455,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352815,-99) , 
5, 2.82943, 1, 0, 0.459336,-99) , 
NN(
0, 
0, 
-1, 1254.46, 0, -1, 0.28413,-99) , 
0, -1.1605, 0, 0, 0.42258,-99) , 
1, 1734.24, 0, 0, 0.470009,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.262264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697548,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498314,-99) , 
2, -2.16751, 1, 0, 0.553503,-99) , 
1, 2134.27, 0, 0, 0.622804,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415941,-99) , 
4, 2.96439, 0, 0, 0.44515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.25419,-99) , 
9, 260.643, 0, 0, 0.420271,-99) , 
1, 1734.24, 0, 0, 0.460907,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.237075);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.507977, 0, 1, 0.607043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389087,-99) , 
0, 1.26438, 1, 0, 0.572361,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44413,-99) , 
4, -2.82602, 1, 0, 0.487964,-99) , 
NN(
0, 
0, 
-1, 1206.81, 0, -1, 0.377187,-99) , 
3, 0.732313, 0, 0, 0.440827,-99) , 
1, 1408.08, 0, 0, 0.494219,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.215915);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395687,-99) , 
3, 0.212397, 0, 0, 0.539588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332589,-99) , 
0, 1.67479, 1, 0, 0.519863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328615,-99) , 
0, -1.68129, 0, 0, 0.502246,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.2013);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469807,-99) , 
0, -0.573743, 0, 0, 0.541522,-99) , 
NN(
0, 
0, 
-1, 2.68819, 1, -1, 0.389369,-99) , 
8, 176.375, 1, 0, 0.514136,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42014,-99) , 
0, -0.255779, 0, 0, 0.493971,-99) , 
NN(
0, 
0, 
-1, 2.346, 0, -1, 0.369115,-99) , 
2, -1.68556, 1, 0, 0.414371,-99) , 
6, 0.415705, 0, 0, 0.481097,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.167431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412627,-99) , 
0, 1.40399, 1, 0, 0.538877,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309554,-99) , 
9, 391.061, 0, 0, 0.449909,-99) , 
8, 141.66, 1, 0, 0.506124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360147,-99) , 
9, 261.796, 0, 0, 0.489259,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.197801);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635698,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427274,-99) , 
1, 1407.41, 0, 0, 0.497889,-99) , 
2, 1.45251, 0, 0, 0.554541,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439174,-99) , 
1, 1213.01, 0, 0, 0.51348,-99) , 
NN(
0, 
0, 
-1, 2.91706, 1, -1, 0.420175,-99) , 
4, 2.88262, 0, 0, 0.450157,-99) , 
4, -2.95717, 1, 0, 0.470941,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.145078);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.64567, 1, 1, 0.564983,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386089,-99) , 
4, 2.17844, 0, 0, 0.487411,-99) , 
4, -2.38474, 1, 0, 0.518438,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362344,-99) , 
8, 216.385, 1, 0, 0.472708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344501,-99) , 
9, 397.132, 0, 0, 0.436698,-99) , 
8, 146.563, 1, 0, 0.493715,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.110189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497539,-99) , 
1, 1593.7, 0, 0, 0.523028,-99) , 
NN(
0, 
0, 
-1, 340.419, 0, -1, 0.455855,-99) , 
8, 116.99, 1, 0, 0.489318,-99) , 
NN(
0, 
0, 
-1, -2.38694, 1, -1, 0.39531,-99) , 
6, 0.178398, 0, 0, 0.47539,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.116176);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471509,-99) , 
0, 0.557459, 1, 0, 0.518615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407862,-99) , 
7, 0.0648793, 0, 0, 0.511205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373764,-99) , 
4, -2.38694, 1, 0, 0.422245,-99) , 
6, 0.178398, 0, 0, 0.498113,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.148223);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458188,-99) , 
9, 551.394, 1, 0, 0.530644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384983,-99) , 
9, 261.796, 0, 0, 0.513391,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434985,-99) , 
5, 2.61486, 1, 0, 0.48418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381835,-99) , 
8, 127.244, 1, 0, 0.440156,-99) , 
0, -0.91288, 0, 0, 0.494253,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.114785);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611133,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441741,-99) , 
0, -0.648394, 0, 0, 0.524281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40352,-99) , 
2, -1.24054, 1, 0, 0.465616,-99) , 
2, 2.37845, 0, 0, 0.4827,-99) , 
1, 2727, 0, 0, 0.487336,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.113708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1907.5, 0, 1, 0.537757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438423,-99) , 
0, -1.23768, 0, 0, 0.519111,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419606,-99) , 
2, -2.84608, 0, 0, 0.477301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370605,-99) , 
2, -1.17837, 1, 0, 0.451478,-99) , 
2, 1.81394, 0, 0, 0.478766,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.133551);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471093,-99) , 
6, 0.414143, 0, 0, 0.520665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417848,-99) , 
3, 0.227673, 0, 0, 0.501705,-99) , 
NN(
NN(
0, 
0, 
-1, 1083.06, 0, -1, 0.467521,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299894,-99) , 
2, -2.81837, 1, 0, 0.385799,-99) , 
5, 2.92229, 1, 0, 0.447913,-99) , 
2, 1.70004, 0, 0, 0.470469,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0510984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597835,-99) , 
NN(
0, 
0, 
-1, 674.942, 1, -1, 0.481557,-99) , 
1, 2727, 0, 0, 0.48571,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.102428);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460488,-99) , 
5, 2.91706, 1, 0, 0.518107,-99) , 
NN(
0, 
0, 
-1, 118.194, 1, -1, 0.451741,-99) , 
1, 1101, 0, 0, 0.503436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391997,-99) , 
9, 697.439, 1, 0, 0.49766,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0864551);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485747,-99) , 
8, 119.546, 1, 0, 0.511364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39184,-99) , 
9, 674.942, 1, 0, 0.504157,-99) , 
NN(
0, 
0, 
-1, -0.208957, 0, -1, 0.429723,-99) , 
5, 1.90058, 0, 0, 0.494228,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0636077);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49863,-99) , 
2, -2.28531, 1, 0, 0.514001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414531,-99) , 
7, 0.0677886, 0, 0, 0.506721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425501,-99) , 
0, 1.57393, 1, 0, 0.498424,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0938629);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.42226, 0, 1, 0.588854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454441,-99) , 
5, 2.94475, 0, 0, 0.503663,-99) , 
5, 2.70147, 1, 0, 0.545028,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402351,-99) , 
7, 0.0726356, 0, 0, 0.50087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425295,-99) , 
0, 1.5096, 1, 0, 0.491899,-99) , 
4, -2.85275, 1, 0, 0.506502,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0962182);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647296,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473257,-99) , 
6, 0.403471, 0, 0, 0.52537,-99) , 
1, 2062.89, 0, 0, 0.536854,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424963,-99) , 
5, 2.20721, 0, 0, 0.498047,-99) , 
NN(
0, 
0, 
-1, 306.852, 0, -1, 0.452514,-99) , 
4, 2.53379, 0, 0, 0.477831,-99) , 
4, -2.85275, 1, 0, 0.494001,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0667955);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499357,-99) , 
2, 2.66033, 0, 0, 0.51438,-99) , 
1, 2239.66, 0, 0, 0.523996,-99) , 
NN(
0, 
0, 
-1, 0.15539, 0, -1, 0.470145,-99) , 
4, -2.38474, 1, 0, 0.492757,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0895723);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462955,-99) , 
9, 344.988, 0, 0, 0.519977,-99) , 
9, 282.325, 1, 0, 0.532642,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429992,-99) , 
4, 0.82065, 0, 0, 0.498352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406731,-99) , 
3, 0.15539, 0, 0, 0.48689,-99) , 
4, -2.38474, 1, 0, 0.506104,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0934552);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499706,-99) , 
6, 0.773584, 1, 0, 0.545426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443957,-99) , 
7, 0.178726, 0, 0, 0.484001,-99) , 
1, 1232.48, 0, 0, 0.520163,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484191,-99) , 
4, 3.06146, 0, 0, 0.502579,-99) , 
NN(
0, 
0, 
-1, -2.38053, 1, -1, 0.451604,-99) , 
2, 0.893726, 0, 0, 0.476014,-99) , 
4, -2.38474, 1, 0, 0.494536,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0712585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484169,-99) , 
1, 1232.25, 0, 0, 0.50898,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408072,-99) , 
5, 2.58402, 1, 0, 0.457517,-99) , 
6, 0.178398, 0, 0, 0.501543,-99) , 
1, 2727, 0, 0, 0.504891,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0588852);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467492,-99) , 
7, 0.118073, 0, 0, 0.502075,-99) , 
1, 2277.16, 0, 0, 0.507114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432947,-99) , 
9, 673.395, 1, 0, 0.502425,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0913014);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47082,-99) , 
7, 0.146245, 0, 0, 0.507477,-99) , 
1, 2325.87, 0, 0, 0.514352,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468049,-99) , 
6, 0.805157, 0, 0, 0.493037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410744,-99) , 
2, -1.17837, 1, 0, 0.47994,-99) , 
2, 1.33182, 0, 0, 0.495733,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.063939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572506,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49343,-99) , 
3, 0.363594, 1, 0, 0.520525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437324,-99) , 
3, 0.643247, 0, 0, 0.479482,-99) , 
9, 349.826, 1, 0, 0.494014,-99) , 
1, 2727, 0, 0, 0.496727,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0975766);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495209,-99) , 
3, 0.786874, 1, 0, 0.553864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430619,-99) , 
5, 2.9096, 1, 0, 0.525662,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43081,-99) , 
4, -3.05712, 0, 0, 0.493708,-99) , 
NN(
0, 
0, 
-1, 0.956845, 1, -1, 0.447543,-99) , 
4, 2.82899, 1, 0, 0.479323,-99) , 
9, 349.826, 1, 0, 0.495784,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.120427);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493762,-99) , 
5, 2.21484, 0, 0, 0.555743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458799,-99) , 
5, 2.89009, 1, 0, 0.531549,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457406,-99) , 
7, 0.180329, 0, 0, 0.501893,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441054,-99) , 
1, 1694.61, 0, 0, 0.458885,-99) , 
5, 2.72806, 0, 0, 0.47618,-99) , 
9, 349.826, 1, 0, 0.495809,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.089442);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.2935, 0, 1, 0.571706,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427864,-99) , 
0, 0.309517, 1, 0, 0.490651,-99) , 
5, 2.6145, 1, 0, 0.531757,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486898,-99) , 
1, 2473.98, 0, 0, 0.491409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418814,-99) , 
9, 699.69, 1, 0, 0.485645,-99) , 
9, 349.826, 1, 0, 0.501981,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.07373);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.796637, 1, 1, 0.524169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436269,-99) , 
3, 0.781483, 0, 0, 0.49094,-99) , 
7, 0.221802, 1, 0, 0.51494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440795,-99) , 
9, 699.69, 1, 0, 0.511153,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0883023);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485128,-99) , 
7, 0.0816773, 1, 0, 0.494472,-99) , 
0, 0.213348, 1, 0, 0.51308,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4889,-99) , 
4, 2.96617, 0, 0, 0.505206,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404764,-99) , 
3, 0.796504, 1, 0, 0.450019,-99) , 
1, 1393.88, 1, 0, 0.48203,-99) , 
0, -0.157354, 0, 0, 0.498509,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0737197);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496034,-99) , 
7, 0.203064, 0, 0, 0.512721,-99) , 
0, 0.153406, 1, 0, 0.525065,-99) , 
NN(
NN(
0, 
0, 
-1, 1251.23, 0, 1, 0.519892,-99) , 
NN(
0, 
0, 
-1, 1541.08, 0, -1, 0.452254,-99) , 
1, 1395.29, 1, 0, 0.491462,-99) , 
0, -0.118662, 0, 0, 0.508972,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0827459);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.671388, 1, 1, 0.580328,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466493,-99) , 
1, 1101, 0, 0, 0.514839,-99) , 
7, 0.111515, 1, 0, 0.528852,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557501,-99) , 
NN(
0, 
0, 
-1, 365.175, 0, -1, 0.478836,-99) , 
9, 278.817, 1, 0, 0.488512,-99) , 
0, -0.118662, 0, 0, 0.509534,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0512805);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.318381, 1, 1, 0.516885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434362,-99) , 
6, 0.0891927, 1, 0, 0.474301,-99) , 
6, 0.178398, 0, 0, 0.510663,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0310025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.74843, 0, 1, 0.507408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44727,-99) , 
8, 47.3673, 0, 0, 0.503325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454653,-99) , 
3, 0.0900426, 0, 0, 0.499933,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0707793);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1923.15, 0, 1, 0.519809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443308,-99) , 
0, -1.34336, 0, 0, 0.50671,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483517,-99) , 
3, 0.991165, 0, 0, 0.496063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429058,-99) , 
2, -1.7392, 1, 0, 0.482619,-99) , 
2, 0.893726, 0, 0, 0.49424,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0315157);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560632,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449971,-99) , 
0, 1.52388, 1, 0, 0.494727,-99) , 
3, 0.995633, 0, 0, 0.499173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440891,-99) , 
3, 0.99847, 1, 0, 0.495079,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0831938);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.86327, 0, 1, 0.554461,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42211,-99) , 
2, -2.78782, 0, 0, 0.480345,-99) , 
5, 2.72803, 0, 0, 0.510201,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561057,-99) , 
NN(
0, 
0, 
-1, 3.00716, 1, -1, 0.474208,-99) , 
4, 3.07581, 0, 0, 0.4805,-99) , 
2, -2.28531, 1, 0, 0.489838,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0441394);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425845,-99) , 
8, 73.1303, 0, 0, 0.497326,-99) , 
8, 61.7873, 1, 0, 0.503808,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393136,-99) , 
8, 107.173, 0, 0, 0.465941,-99) , 
4, 3.03214, 1, 0, 0.498696,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0327937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56287,-99) , 
NN(
0, 
0, 
-1, 0.221802, 1, -1, 0.490581,-99) , 
1, 2727, 0, 0, 0.492865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440484,-99) , 
2, -3.0217, 0, 0, 0.490103,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0618698);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490113,-99) , 
3, 0.796637, 1, 0, 0.508878,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454782,-99) , 
9, 504.054, 0, 0, 0.479352,-99) , 
7, 0.221802, 1, 0, 0.500554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448596,-99) , 
2, -3.0217, 0, 0, 0.497819,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0476336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554867,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497346,-99) , 
3, 0.140742, 1, 0, 0.502775,-99) , 
9, 504.21, 0, 0, 0.506906,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406421,-99) , 
3, 0.849055, 0, 0, 0.46944,-99) , 
9, 551.439, 1, 0, 0.500167,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0494886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -3.00613, 1, 1, 0.51487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417976,-99) , 
3, 0.849055, 0, 0, 0.468798,-99) , 
9, 551.439, 1, 0, 0.506598,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0494248);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495293,-99) , 
3, 0.978729, 0, 0, 0.50535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426823,-99) , 
2, 1.78293, 0, 0, 0.467707,-99) , 
5, 3.0065, 1, 0, 0.500172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445204,-99) , 
3, 0.0900426, 0, 0, 0.496338,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0837386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.320656, 1, 1, 0.528232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449632,-99) , 
2, 2.14577, 0, 0, 0.478092,-99) , 
5, 2.86313, 1, 0, 0.513595,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485012,-99) , 
5, 2.69046, 0, 0, 0.509791,-99) , 
NN(
0, 
0, 
-1, 0.181565, 0, -1, 0.453185,-99) , 
3, 0.845465, 0, 0, 0.482806,-99) , 
9, 444.879, 1, 0, 0.502053,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0422828);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 258.421, 1, 1, 0.508826,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406665,-99) , 
5, 2.64232, 0, 0, 0.462069,-99) , 
4, 3.03214, 1, 0, 0.502379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449503,-99) , 
3, 0.998461, 1, 0, 0.498687,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.042634);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487127,-99) , 
4, 1.94529, 1, 0, 0.522771,-99) , 
NN(
0, 
0, 
-1, 0.477706, 0, -1, 0.48826,-99) , 
3, 0.363594, 1, 0, 0.493852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451873,-99) , 
3, 0.0900426, 0, 0, 0.490932,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.049716);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 317.807, 1, 1, 0.520658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485366,-99) , 
2, 2.74843, 0, 0, 0.494284,-99) , 
4, 2.77627, 0, 0, 0.502687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462457,-99) , 
3, 0.0900426, 0, 0, 0.499893,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_VBF0LowVPtHighMJJ::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_VBF0LowVPtHighMJJ::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
