// Class: ReadBDT_VBF0LowVPt
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_VBF0LowVPt
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : ajafari
Date           : Fri Jul  5 15:32:45 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/ajafari/Vjj/CMSSW_9_4_2/src/TopLJets2015/TopAnalysis/macro/mva
Training events: 38803
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
nCuts: "0" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "6.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
circularity                   circularity                   circularity                   circularity                                                     'F'    [0.00168784300331,0.904429256916]
mjj                           mjj                           mjj                           mjj                                                             'F'    [500.103668213,9690.50488281]
jjpt                          jjpt                          jjpt                          jjpt                                                            'F'    [1.5927734375,636.596374512]
dphijj                        dphijj                        dphijj                        dphijj                                                          'F'    [-3.14158821106,3.14154911041]
ystar                         ystar                         ystar                         ystar                                                           'F'    [-4.08989429474,3.85500383377]
relbpt                        relbpt                        relbpt                        relbpt                                                          'F'    [0.592023968697,16.3601665497]
dphibjj                       dphibjj                       dphibjj                       dphibjj                                                         'F'    [-3.14158558846,3.14157009125]
j_qg[0]                       j_qg_0_                       j_qg[0]                       leadjet_qg                                                      'F'    [-1,1]
j_qg[1]                       j_qg_1_                       j_qg[1]                       subleadjet_qg                                                   'F'    [-1,1]
dphivj0                       dphivj0                       dphivj0                       dphivj0                                                         'F'    [0.00120949745178,3.14153504372]
D                             D                             D                             D                                                               'F'    [2.80971448365e-12,0.354771703482]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_VBF0LowVPtNode
   
#ifndef BDT_VBF0LowVPtNode__def
#define BDT_VBF0LowVPtNode__def
   
class BDT_VBF0LowVPtNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_VBF0LowVPtNode ( BDT_VBF0LowVPtNode* left,BDT_VBF0LowVPtNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_VBF0LowVPtNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_VBF0LowVPtNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_VBF0LowVPtNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_VBF0LowVPtNode*   fLeft;     // pointer to the left daughter node
   BDT_VBF0LowVPtNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_VBF0LowVPtNode::~BDT_VBF0LowVPtNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_VBF0LowVPtNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_VBF0LowVPtNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_VBF0LowVPt : public IClassifierReader {

 public:

   // constructor
   ReadBDT_VBF0LowVPt( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_VBF0LowVPt" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "circularity", "mjj", "jjpt", "dphijj", "ystar", "relbpt", "dphibjj", "j_qg[0]", "j_qg[1]", "dphivj0", "D" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_VBF0LowVPt() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_VBF0LowVPtNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_VBF0LowVPt::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_VBF0LowVPtNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_VBF0LowVPtNode*)current->GetRight();
         else current=(BDT_VBF0LowVPtNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_VBF0LowVPt::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.479507684900871);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 157.846, 1, 1, 0.825497,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334548,-99) , 
4, -1.45311, 0, 0, 0.582978,-99) , 
1, 1727.08, 0, 0, 0.637724,-99) , 
NN(
0, 
0, 
-1, 611.348, 0, -1, 0.278949,-99) , 
1, 894.866, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.279304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.00164, 0, 1, 0.718727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457959,-99) , 
4, 1.06953, 1, 0, 0.666605,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.312424,-99) , 
5, 1.48619, 0, 0, 0.477924,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254635,-99) , 
4, 1.21789, 1, 0, 0.434318,-99) , 
1, 1404.56, 0, 0, 0.490844,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.210682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.50789, 0, 1, 0.711593,-99) , 
NN(
0, 
0, 
-1, 611.348, 0, -1, 0.430852,-99) , 
1, 1727.08, 0, 0, 0.465825,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.271823);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364927,-99) , 
4, 1.49766, 1, 0, 0.560008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334461,-99) , 
4, -1.68129, 0, 0, 0.539941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333254,-99) , 
1, 636.335, 0, 0, 0.508121,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.187358);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449269,-99) , 
8, 0.200433, 0, 0, 0.609576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426033,-99) , 
2, 176.375, 1, 0, 0.57581,-99) , 
NN(
0, 
0, 
-1, 0.204501, 0, -1, 0.44188,-99) , 
1, 1250.89, 0, 0, 0.48516,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.223192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466519,-99) , 
4, 0.786018, 1, 0, 0.563747,-99) , 
NN(
0, 
0, 
-1, 1040.06, 0, -1, 0.421908,-99) , 
4, -1.16086, 0, 0, 0.537219,-99) , 
NN(
0, 
0, 
-1, 0.454579, 0, -1, 0.374501,-99) , 
7, 0.200439, 0, 0, 0.513129,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.198832);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2133.9, 0, 1, 0.564973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41899,-99) , 
9, 1.61503, 0, 0, 0.551135,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458495,-99) , 
0, 0.165094, 1, 0, 0.542949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327919,-99) , 
5, 2.11006, 0, 0, 0.42918,-99) , 
9, 2.89674, 1, 0, 0.520537,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.115154);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672118,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479483,-99) , 
6, 2.97221, 0, 0, 0.498264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348248,-99) , 
7, 0.0900803, 0, 0, 0.48652,-99) , 
1, 2133.9, 0, 0, 0.496533,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.143274);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.70021, 1, 1, 0.588709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463259,-99) , 
5, 2.26781, 0, 0, 0.502371,-99) , 
6, -2.91051, 1, 0, 0.523832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381466,-99) , 
7, 0.0900803, 0, 0, 0.512967,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.14382);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659576,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48167,-99) , 
8, 0.451568, 0, 0, 0.541177,-99) , 
1, 1489.72, 0, 0, 0.561342,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39773,-99) , 
2, 174.924, 1, 0, 0.504958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395683,-99) , 
5, 1.70249, 0, 0, 0.477561,-99) , 
0, 0.507504, 0, 0, 0.510535,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.130274);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.91744, 1, 1, 0.573992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486845,-99) , 
1, 772.201, 0, 0, 0.545742,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467324,-99) , 
6, 2.99923, 0, 0, 0.485799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388166,-99) , 
8, 0.237142, 0, 0, 0.467309,-99) , 
0, 0.507504, 0, 0, 0.498125,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.12496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701234,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461171,-99) , 
7, 0.477655, 0, 0, 0.520732,-99) , 
1, 2227.01, 0, 0, 0.528812,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422785,-99) , 
1, 934.084, 0, 0, 0.47248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388268,-99) , 
2, 146.629, 1, 0, 0.449995,-99) , 
4, -0.887806, 0, 0, 0.508476,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.12307);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499321,-99) , 
8, 0.483772, 0, 0, 0.569422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474067,-99) , 
1, 1721.97, 0, 0, 0.489456,-99) , 
4, 0.432366, 1, 0, 0.519723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534089,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429665,-99) , 
6, -2.95745, 1, 0, 0.447194,-99) , 
5, 1.57356, 1, 0, 0.464262,-99) , 
4, -0.458039, 0, 0, 0.499168,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.119373);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 114.538, 1, 1, 0.576568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46572,-99) , 
6, 2.62348, 0, 0, 0.511154,-99) , 
6, -2.7942, 1, 0, 0.531598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431117,-99) , 
3, -2.01458, 1, 0, 0.457278,-99) , 
6, 2.97236, 0, 0, 0.473346,-99) , 
4, -0.458039, 0, 0, 0.510019,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.133465);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -2.83836, 1, 1, 0.57714,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490253,-99) , 
5, 1.82582, 1, 0, 0.511369,-99) , 
7, 0.943074, 0, 0, 0.535451,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47937,-99) , 
4, -0.396427, 0, 0, 0.522013,-99) , 
NN(
0, 
0, 
-1, 1.43823, 1, -1, 0.37181,-99) , 
3, -1.28388, 1, 0, 0.481806,-99) , 
3, 1.78887, 0, 0, 0.503045,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.111153);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427763,-99) , 
3, -2.97323, 0, 0, 0.528703,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439574,-99) , 
5, 1.8724, 1, 0, 0.473019,-99) , 
2, 144.281, 1, 0, 0.513185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417678,-99) , 
1, 577.94, 0, 0, 0.505046,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0782618);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591034,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490521,-99) , 
6, -2.70141, 1, 0, 0.509597,-99) , 
NN(
0, 
0, 
-1, 0.351704, 0, -1, 0.460764,-99) , 
10, 0.00290219, 0, 0, 0.488733,-99) , 
1, 2133.9, 0, 0, 0.493945,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0975145);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483641,-99) , 
8, 0.353513, 0, 0, 0.549026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484412,-99) , 
4, -0.887806, 0, 0, 0.532015,-99) , 
NN(
NN(
0, 
0, 
-1, 1404.55, 0, 1, 0.515855,-99) , 
NN(
0, 
0, 
-1, 1.43823, 1, -1, 0.405847,-99) , 
3, -1.24054, 1, 0, 0.486645,-99) , 
3, 1.82439, 0, 0, 0.504404,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0961976);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486346,-99) , 
2, 83.0712, 0, 0, 0.520263,-99) , 
1, 1942, 0, 0, 0.527754,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475972,-99) , 
1, 1404.55, 0, 0, 0.490751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387806,-99) , 
3, -1.03989, 1, 0, 0.472284,-99) , 
3, 1.45301, 0, 0, 0.496674,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0612528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1913.56, 0, 1, 0.532054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421366,-99) , 
9, 2.98972, 1, 0, 0.493748,-99) , 
3, 2.14339, 0, 0, 0.506579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428676,-99) , 
4, 1.79179, 1, 0, 0.501024,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0866087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.04303, 0, 1, 0.54053,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451666,-99) , 
8, 0.752952, 1, 0, 0.487032,-99) , 
5, 2.85566, 1, 0, 0.518619,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438291,-99) , 
10, 0.000278372, 0, 0, 0.50283,-99) , 
NN(
0, 
0, 
-1, 0.402198, 0, -1, 0.457654,-99) , 
3, -1.96281, 1, 0, 0.480413,-99) , 
3, 2.37933, 0, 0, 0.490677,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.060847);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552277,-99) , 
NN(
NN(
0, 
0, 
-1, 1942, 0, 1, 0.507356,-99) , 
NN(
0, 
0, 
-1, -1.28404, 1, -1, 0.466434,-99) , 
3, 1.78887, 0, 0, 0.483834,-99) , 
5, 1.32896, 1, 0, 0.490503,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.102537);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474583,-99) , 
5, 2.1865, 1, 0, 0.516336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445934,-99) , 
3, -2.55401, 1, 0, 0.476592,-99) , 
0, 0.40896, 0, 0, 0.499931,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508856,-99) , 
NN(
0, 
0, 
-1, 1232.24, 0, -1, 0.425392,-99) , 
2, 94.9109, 1, 0, 0.456366,-99) , 
5, 3.07306, 1, 0, 0.491107,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0477386);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437443,-99) , 
7, 0.998368, 1, 0, 0.501331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433348,-99) , 
7, 0.0900803, 0, 0, 0.496173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419785,-99) , 
2, 44.0722, 0, 0, 0.491501,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0714471);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534842,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472459,-99) , 
1, 893.835, 1, 0, 0.485907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428362,-99) , 
1, 597.286, 0, 0, 0.480217,-99) , 
5, 1.28157, 1, 0, 0.484452,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.105258);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481269,-99) , 
9, 2.46889, 0, 0, 0.560372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445579,-99) , 
6, -2.38478, 1, 0, 0.495498,-99) , 
6, 2.88261, 0, 0, 0.511497,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480948,-99) , 
7, 0.880529, 0, 0, 0.503962,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433518,-99) , 
10, 0.017217, 0, 0, 0.454936,-99) , 
8, 0.864622, 0, 0, 0.474152,-99) , 
1, 1100.03, 0, 0, 0.49079,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0960969);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440477,-99) , 
5, 3.52797, 1, 0, 0.530925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462864,-99) , 
3, -2.14943, 1, 0, 0.48312,-99) , 
8, 0.638465, 0, 0, 0.509167,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467872,-99) , 
2, 113.535, 1, 0, 0.493516,-99) , 
NN(
0, 
0, 
-1, 1.58394, 1, -1, 0.429617,-99) , 
6, -2.38474, 1, 0, 0.47954,-99) , 
6, 2.19161, 0, 0, 0.493006,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0774025);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486486,-99) , 
5, 3.10365, 1, 0, 0.563535,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438307,-99) , 
5, 2.45212, 0, 0, 0.493607,-99) , 
7, 0.796637, 1, 0, 0.525962,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48942,-99) , 
2, 148.854, 0, 0, 0.501887,-99) , 
NN(
0, 
0, 
-1, -1.43919, 1, -1, 0.472483,-99) , 
3, 1.27759, 0, 0, 0.485599,-99) , 
1, 1408.48, 0, 0, 0.494574,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0429824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2277.17, 0, 1, 0.514322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462958,-99) , 
4, -1.7627, 0, 0, 0.510015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460285,-99) , 
4, 1.79179, 1, 0, 0.506469,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0581154);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488403,-99) , 
10, 0.00290974, 0, 0, 0.509688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42264,-99) , 
4, -0.706908, 0, 0, 0.478181,-99) , 
5, 3.07306, 1, 0, 0.502707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45836,-99) , 
1, 577.94, 0, 0, 0.498931,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0468765);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555963,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494131,-99) , 
8, 0.964872, 0, 0, 0.502088,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445642,-99) , 
1, 1503.87, 0, 0, 0.46659,-99) , 
5, 3.07218, 1, 0, 0.49519,-99) , 
0, 0.09959, 1, 0, 0.498605,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0449701);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2133.64, 0, 1, 0.511276,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467701,-99) , 
4, -0.0392785, 1, 0, 0.493953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440293,-99) , 
4, -0.706908, 0, 0, 0.47626,-99) , 
5, 3.07306, 1, 0, 0.504174,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0641443);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.0758, 0, 1, 0.517511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459287,-99) , 
3, -2.84608, 0, 0, 0.509513,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480995,-99) , 
1, 796.045, 0, 0, 0.494102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426616,-99) , 
1, 893.835, 1, 0, 0.481983,-99) , 
1, 1019.17, 0, 0, 0.496728,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0561574);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536298,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497338,-99) , 
7, 0.990179, 0, 0, 0.512942,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454056,-99) , 
3, 2.09733, 0, 0, 0.482533,-99) , 
3, -2.28531, 1, 0, 0.492188,-99) , 
5, 1.28157, 1, 0, 0.495645,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0974019);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44982,-99) , 
3, -2.78655, 0, 0, 0.499257,-99) , 
9, 2.84049, 0, 0, 0.519184,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474322,-99) , 
5, 1.82607, 1, 0, 0.501696,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433217,-99) , 
3, 2.46559, 0, 0, 0.46629,-99) , 
9, 2.68316, 1, 0, 0.486486,-99) , 
3, -2.28531, 1, 0, 0.496248,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0386183);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576071,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490666,-99) , 
5, 1.59452, 1, 0, 0.497454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446064,-99) , 
7, 0.998796, 1, 0, 0.494361,-99) , 
1, 2601.84, 0, 0, 0.496318,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0720241);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491411,-99) , 
2, 141.639, 1, 0, 0.533403,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474363,-99) , 
6, -0.464088, 0, 0, 0.495768,-99) , 
4, -0.174688, 0, 0, 0.509091,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479867,-99) , 
8, 0.539116, 1, 0, 0.504591,-99) , 
NN(
0, 
0, 
-1, 106.677, 0, -1, 0.457128,-99) , 
10, 0.00225059, 0, 0, 0.484294,-99) , 
4, 0.7872, 1, 0, 0.501711,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0289854);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558884,-99) , 
NN(
NN(
0, 
0, 
-1, 0.702674, 0, 1, 0.505495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420651,-99) , 
2, 107.213, 0, 0, 0.472813,-99) , 
6, 3.02683, 1, 0, 0.50067,-99) , 
1, 2226.98, 0, 0, 0.503135,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0488437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551726,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492174,-99) , 
2, 153.461, 0, 0, 0.498813,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413788,-99) , 
10, 0.00599622, 0, 0, 0.466546,-99) , 
8, 0.17892, 0, 0, 0.494275,-99) , 
1, 2226.98, 0, 0, 0.496705,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0431095);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.978196, 0, 1, 0.510724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459183,-99) , 
7, 0.998383, 1, 0, 0.506869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4271,-99) , 
0, 0.450905, 0, 0, 0.473415,-99) , 
8, 0.169996, 0, 0, 0.502372,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0341264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.488617, 0, 1, 0.543138,-99) , 
NN(
0, 
0, 
-1, 0.620492, 0, -1, 0.492532,-99) , 
7, 0.364491, 1, 0, 0.498349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466366,-99) , 
7, 0.157635, 0, 0, 0.494511,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0205304);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541409,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499109,-99) , 
1, 2133.84, 0, 0, 0.501815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454176,-99) , 
5, 4.20856, 1, 0, 0.498638,-99) , 
9, 1.52516, 1, 0, 0.501332,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0564807);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487423,-99) , 
9, 2.72793, 0, 0, 0.507363,-99) , 
7, 0.989816, 0, 0, 0.522076,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494346,-99) , 
6, -2.70092, 1, 0, 0.51137,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433006,-99) , 
3, 2.09384, 0, 0, 0.4784,-99) , 
0, 0.396163, 0, 0, 0.49923,-99) , 
3, -2.38368, 1, 0, 0.505456,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0519491);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.153006, 1, 1, 0.55223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49935,-99) , 
8, 0.992657, 0, 0, 0.507581,-99) , 
10, 0.00143341, 1, 0, 0.516679,-99) , 
NN(
NN(
0, 
0, 
-1, 2.33476, 1, 1, 0.523385,-99) , 
NN(
0, 
0, 
-1, 2.74805, 0, -1, 0.471012,-99) , 
3, -2.24972, 1, 0, 0.492006,-99) , 
0, 0.396933, 0, 0, 0.505819,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0657171);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.65989, 0, 1, 0.524247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496984,-99) , 
7, 0.154035, 0, 0, 0.521095,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467055,-99) , 
0, 0.259945, 1, 0, 0.506172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435504,-99) , 
8, 0.979446, 1, 0, 0.491413,-99) , 
0, 0.346731, 0, 0, 0.510168,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0409712);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49398,-99) , 
7, 0.724067, 1, 0, 0.531846,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47489,-99) , 
10, 0.000853674, 0, 0, 0.500755,-99) , 
1, 1549.54, 0, 0, 0.50507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463694,-99) , 
5, 4.20871, 1, 0, 0.502084,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0511996);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534011,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474222,-99) , 
5, 2.80225, 1, 0, 0.500786,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417617,-99) , 
5, 2.11014, 0, 0, 0.473331,-99) , 
2, 73.1303, 0, 0, 0.496053,-99) , 
9, 1.52516, 1, 0, 0.498447,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0653775);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470482,-99) , 
7, 0.724523, 1, 0, 0.493639,-99) , 
6, 2.882, 0, 0, 0.505307,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466419,-99) , 
6, 2.90757, 1, 0, 0.499314,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451719,-99) , 
8, 0.897313, 0, 0, 0.47211,-99) , 
7, 0.795784, 0, 0, 0.486606,-99) , 
1, 1232.25, 0, 0, 0.4927,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.05536);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453026,-99) , 
8, 0.178398, 0, 0, 0.508974,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479678,-99) , 
5, 1.38839, 1, 0, 0.485375,-99) , 
1, 1232.25, 0, 0, 0.49305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447729,-99) , 
8, 0.998116, 1, 0, 0.490958,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.078428);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48825,-99) , 
0, 0.331051, 0, 0, 0.51412,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462328,-99) , 
7, 0.963772, 0, 0, 0.482469,-99) , 
2, 116.776, 1, 0, 0.500534,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55489,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480798,-99) , 
5, 1.44211, 1, 0, 0.521623,-99) , 
NN(
0, 
0, 
-1, 0.60182, 1, -1, 0.445176,-99) , 
2, 121.124, 0, 0, 0.480667,-99) , 
5, 1.69928, 0, 0, 0.495134,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_VBF0LowVPt::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_VBF0LowVPt::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
