FILES={
    'pp_5TeV':(['file:root://eoscms//eos/cms/store/group/phys_heavyions/azsigmon/TagAndProbe2015/TnP_Z_pp5TeV_data_trk_v4.root'],
               ['file:root://eoscms//eos/cms/store/group/phys_heavyions/azsigmon/TagAndProbe2015/TnP_Z_pp5TeV_MC_Zmu10mu10_trk_v4.root']),       
    'pPb_8.16TeV':(['file:/eos/user/g/gkrintir/output_pPb/TnpTrees/PASingleMuon_PARun2016C-PromptReco-v1TnpTress_Pbpv1.root'],
                   ['file:/eos/user/g/gkrintir/output_pPb/TnpTrees/Pyquen_DYtoLL_M_30to10000_embd_pPb_echapon-step3_80X_mcRun2_pA_v4-v1.root']),
    'pPb_noembed_8.16TeV':(['file:/eos/user/g/gkrintir/output_pPb/TnpTrees/PASingleMuon_PARun2016C-PromptReco-v1TnpTress_Pbpv2.root',
                            'file:/eos/user/g/gkrintir/output_pPb/TnpTrees/PASingleMuon_PARun2016C-PromptReco-v1TnpTress_pPbv2.root'],
                           ['file:/eos/user/g/gkrintir/output_pPb/TnpTrees/DYtoMuMu_M-30_PbP-Bst_8p16TeV-Pyquen_pPb816Summer16DR-PbPBst_80X_mcRun2_pA_v4-v1_WithL3Filter.root',
                            'file:/eos/user/g/gkrintir/output_pPb/TnpTrees/DYtoMuMu_M-30_pPb-Bst_8p16TeV-Pyquen_pPb816Summer16DR-pPbBst_80X_mcRun2_pA_v4-v1_WithL3Filter.root'])
    }
